#spring:
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost;databaseName=pertoriLab;encrypt=true;trustservercertificate=true;
#    username: sa
#    password: 123
#
#  jpa:
#    database-platform: org.hibernate.dialect.SQLServerDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: none

#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10706971?useSSL=false&serverTimezone=UTC
#    username: sql10706971
#    password: BDsqxqMQ7B
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: false
#    hibernate:
#      ddl-auto: none

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ep-steep-star-a16jbdcv.ap-southeast-1.aws.neon.tech/pertory_lab
    username: pertory_lab_owner
    password: 3TCavXynFEJ6

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 535160425613901
            client-secret: b1b2cf6a4abe8f6d5df48cd7245025d3

          google:
            client-id: "417810170630-1960svakd53j9uf565vbmgu2a2vc88vr.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile
  mail:
      host : smtp.gmail.com
      port : 587
      username: ngadxph30395@fpt.edu.vn
      password : zncespnsdqqiglae
      properties :
        mail:
          smtp:
              auth: true
              starttls:
                enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
