#spring:
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost;databaseName=pertoriLab;encrypt=true;trustservercertificate=true;
#    username: sa
#    password: 123
#
#  jpa:
#    database-platform: org.hibernate.dialect.SQLServerDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: none

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10706971?useSSL=false&serverTimezone=UTC
    username: sql10706971
    password: BDsqxqMQ7B

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

  mail:
      host : smtp.gmail.com
      port : 587
      username: ngadxph30395@fpt.edu.vn
      password : zncespnsdqqiglae
      properties :
        mail:
          smtp:
              auth: true
              starttls:
                enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
